### ISSUE TITLE
NeoVim color scheme

### ISSUE THREAD

**Issue by Miyan0** [gerryhjs/gerry-themes-vscode#1]
Sorry to post this here but I don't use Slack.

I love your themes , and use `Gerry+ Dark(Pro)` in all Jetbrains products. When I saw that you're now adding support for VSCode, I was wondering if you've considered adding Neovim support later (after you're done with the VSCode version).

Thanks for your nice work

**Comment by gerryhjs** [comment]
Currently VSCode is only IDE on plan, but I may consider to add other IDEs support in future.
